### ISSUE TITLE
How to execute included datasets?

### ISSUE THREAD

**Issue by forksup** [pucrs-automated-planning/diverse-plan-rec#1]
Hello,

I have found this implementation and am hoping to use it in my own publication. I have searched through the code and found the pyperplan repository which is made to run the included benchmarks. However, I do not see any logic for running the included datasets through the planner so we can generate State traces.

What am I missing or has this just not been implemented? 

Thanks!

**Comment by meneguzzi** [comment]
Hi, I'm not sure I understand your question. Also, it is possible that this implementation is incomplete or incorrect (@ramonpereira , I don't recall if we did finish this), because we had an issue with the authors of the paper on goal recognition by diverse planning complaining about the results we got.

**Comment by forksup** [comment]
> Hi, I'm not sure I understand your question. Also, it is possible that this implementation is incomplete or incorrect (@ramonpereira , I don't recall if we did finish this), because we had an issue with the authors of the paper on goal recognition by diverse planning complaining about the results we got.

Hi Felipe,

Thanks for your response. I do believe this implementation is incomplete. I have however found your pyperplan planner implementation useful. Do you have any tips for converting the pyperplan domains into a set of categorical based variable representation?

For example in the satellite domain there is the predicate:
(pointing satellite_0 phenomenon_0)

This would thus be converted into:

pointing_satellite_0 = phenomenom_0

**Comment by meneguzzi** [comment]
Hi,

I'm extremely sorry for not responding this on time (probably too late), but just so I don't officially leave you hanging here, what you are asking is a conversion to the finite domain representation that Fast Downward (and other planners) use. I'd use their parser to do that.

Best wishes,

Felipe
